#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1

PROG=/usr/bin/clash
CONFIG_PATH=/etc/clash
WORK_DIR=/tmp/clash

start_service() {
	# Remove existing link or folder
	rm -rf $WORK_DIR

	# Create link or copy files from CONFIG_PATH to config_path
	if [ -n "$CONFIG_PATH" ]; then
		if [ ! -d "$CONFIG_PATH" ]; then
			echo "clash config_path does not exist: $CONFIG_PATH" 1>&2
			return
		fi

		# ensure that the target exists
		mkdir -p $WORK_DIR
		cp -r $CONFIG_PATH/* $WORK_DIR
	fi

	$CONFIG_PATH/start_clash.sh

	procd_open_instance
	procd_set_param command $PROG -d $WORK_DIR
	procd_set_param stderr 1
	procd_set_param respawn
	procd_close_instance
}

stop_service() {
	$CONFIG_PATH/stop_clash.sh
	# Remove existing link or folder
	rm -rf $WORK_DIR
}
