#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

PROG=/usr/bin/mosdns

start_service() {
    if [ ! -d /tmp/geodata ]; then
        cp -r /usr/share/geodata /tmp
    fi

    cp -r /etc/mosdns /tmp/

    procd_open_instance mosdns
    procd_set_param env QUIC_GO_DISABLE_RECEIVE_BUFFER_WARNING=true
    procd_set_param command $PROG start
    procd_append_param command -c "/etc/mosdns/config.yaml"
    procd_append_param command -d "/etc/mosdns"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn
    procd_close_instance mosdns
}
